### ISSUE TITLE
is there a way to Alphaimpute2 only impute samples in input file?

### ISSUE THREAD

**Issue by mmudado** [AlphaGenes/AlphaImpute2#8]
AlphaImpute2 is taking a long time ro run and a huge amount of memory due the to imputation genotypes of samples present in the whole pedigree file. Is there a way to impute genotypes only from the samples present in the genotype input file? I tried the -onlykeyed flag but it is not working.

**Comment by gregorgorjanc** [comment]
Hi @mmudado, we are a bit slim with time and resources, but it would be very useful if you can give us some more details on:

1) the number of individuals in your pedigree,
2) the number of individuals genotyped, and
3) runtime 

Thanks!

**Comment by mmudado** [comment]
Hi Gregor,

1. 18772
2. 582
3. around 3 days
4. ~600 GB RAM utilized.

Thanks,

**Comment by gregorgorjanc** [comment]
Hi @mmudado this indeed looks excessive!

Can you also provide number of markers and the number of chromosomes these markers are spread over?

**Comment by mmudado** [comment]
Hi,

Number of markers 537337
Number of chromosomes 30

We are trying to impute 50 samples from 35169 to 537337 markers. We are
using 532 samples fully genotyped with 537337 markers.
The time spent in the last AI2 run was :

Full Program Run: 132048.70 seconds

Thanks!

**Comment by gregorgorjanc** [comment]
@mmudado is it faster if you do one chromosome at a time? Then you can do them in parallel. You could also prune pedigree before imputation given that your only imputing 50 individuals.

**Comment by mmudado** [comment]
Could I prune the pedigree file without losing accuracy?

**Comment by gregorgorjanc** [comment]
@mmudado this will depend on your pedigree. To summarise you have

pedigree: 18772
genotyped@500K: 532
genotyped@35K: 50

How "far" are your 50 animals from the 532 animals?

If you really want to leverage pedigree information in imputation, then I suspect the 50 are closely related to the 532. Since most of your pedigree is not-genotyped, you can prune out animals that will not provide any information to imputation - see http://didgeridoo.une.edu.au/km/prune.php this tool is for genetic evaluation (BLUP), but the principle is the same - individuals at the top of pedigree with only one progeny and no genotype data, or individuals at the bottom of pedigree with no genotype data don't contribute any information. I guess you will be able to shave of a lot of individuals. Doing chromosome by chromosome will help too.

If they are not closely related, you will not benefit from pedigree imputation and you can then use other population based approaches using Hidden Markov Models (say IMPUTE, IMPUTE2, ...).

**Comment by mmudado** [comment]
Thanks!
